### ISSUE TITLE
What does "RA" and "gyro" means in the datasets?

### ISSUE THREAD

**Issue by JW-Yuan** [Juneeee98/Realtime-Fall-Dectection-and-Human-Activity-Recognition-Using-MLP#1]
Thank you a lot for helping me! Whether "gyro" means "angular velocity" , "angular acceleration" or "angle"?

**Comment by Juneeee98** [comment]
RA is Raising Arm, like the raise to wake in apple watch. Gyro is the angle in degrees.

**Comment by JW-Yuan** [comment]
Thank you so much!
